feat: adding Kotlin examples for Working with Items
aws-samples/aws-dynamodb-examples pull request #154
Opened 2024-10-09 07:45 UTC by plastic-karma

https://github.com/aws-samples/aws-dynamodb-examples/issues/153

2024-10-30 00:19 UTC, tebanieo requested changes
Sorry it took me so long to review this code. Can you please match the read operations with the ids that you wrote? instead of using `YourPrimaryKeyValue` can you use the `1234` and `1235` examples you wrote in the operations? I started commenting on the individuals but I realized it was the same across the examples.

2024-10-30 00:19 UTC, tebanieo commented on examples/SDK/kotlin/data_plane/WorkingWithItems/src/main/kotlin/BatchGetItem.kt
> +            mapOf("PrimaryKey" to AttributeValue.S("YourPrimaryKeyValue1")),
It is nice if you match the `PrimaryKeyValue1` and `PrimaryKeyValue2` to the examples `1234` and `1235` that you created with the Write operations, just for uniformity. 

For a new user it will also help on the understanding.

2024-10-30 00:19 UTC, tebanieo commented on examples/SDK/kotlin/data_plane/WorkingWithItems/src/main/kotlin/DeleteItem.kt
> +    val key = mapOf("PrimaryKey" to AttributeValue.S("YourPrimaryKeyValue"))
Same comment than the `BatchGetItem.kt` file, please match with the ids that are written.

2025-04-11 14:13 UTC, plastic-karma commented
@tebanieo Apologies that this took forever (had a kid in the meantime :-) ). I made the changes you requested

2025-06-10 14:18 UTC, merged